name: myan_player
description: A cross Platform video player that uses video_player for android and ios and web, fvp for windows and linux and macos.
version: 4.3.3
homepage: "https://github.com/96coder/myan_player"
environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"
topics:
  - video-player
  - video
  - player
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  video_player: ^2.7.0
  volume_controller: ^2.0.3
  auto_orientation: ^2.3.1
  screen_brightness: ^1.0.0
  flutter_meedu: ^8.0.0+1
  flutter_spinkit: ^5.1.0
  meta: ^1.7.0
  universal_platform: ^1.0.0+1
  fullscreen_window: ^1.0.4
  # video_player_cross_platform:
  #    path: ../../video_player_cross_platform
  fvp: ^0.3.0
  # fvp:
  #   git: https://github.com/wang-bin/fvp
  # fvp:
  #   path: ../../fvp
  window_manager: ^0.3.5
  # window_manager: 
  #   path: ../../window_manager
  # wakelock: ^0.6.1+2
  wakelock_plus: ^1.1.1
  shared_preferences: ^2.0.13
  path_provider: ^2.0.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  
flutter:
  plugin:
    platforms:
      android:
        package: com.zezo357.flutter_meedu_videoplayer
        pluginClass: FlutterMeeduVideoplayerPlugin
      ios:
        pluginClass: FlutterMeeduVideoplayerPlugin
      linux:
        pluginClass: FlutterMeeduVideoplayerPlugin
      macos:
        pluginClass: FlutterMeeduVideoplayerPlugin
      windows:
        pluginClass: FlutterMeeduVideoplayerPluginCApi
      web:
        pluginClass: FlutterMeeduVideoplayerWeb
        fileName: flutter_meedu_videoplayer_web.dart

      # web:
      #   pluginClass: FlutterMeeduVideoplayerPlugin
      #web:
      #pluginClass: FlutterMeeduVideoplayerWeb
      #fileName: flutter_meedu_videoplayer_web.dart
  assets:
    - assets/icons/fast-forward.png
    - assets/icons/fullscreen.png
    - assets/icons/minimize.png
    - assets/icons/mute.png
    - assets/icons/play.png
    - assets/icons/pause.png
    - assets/icons/repeat.png
    - assets/icons/rewind.png
    - assets/icons/sound.png
    - assets/icons/picture-in-picture.png
    - assets/icons/exit_picture-in-picture.png
    - assets/icons/lock-screen.png
    - assets/icons/exit_lock-screen.png
    - assets/icons/fit.png
    
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  